kubewarden/docs

- src/writing-policies/index.md
Recreated https://github.com/kubewarden/docs/pull/14 after it got closed by the master -> main rename.
Revisit the "writing policies" page
* Explain what kubewarden policies are
* Provide a low level overview of the communication protocol
used to communicate with policies. This is useful when new languages
are going to be added, new SDKs are going to be written,...
This PR is built on top of https://github.com/kubewarden/docs/pull/15
This PR addresses this issue: #1
> Writing policies

- src/quick-start.md
> add missing namespace qualifier

- src/quick-start.md
also unify on "shell" highlighting
> don't offer copy&paste for console output

- src/writing-policies/spec/05-context-aware-policies.md
This is some temporary data, we need to dig deeper into the topic
> Added draft version for the context aware policies

- .github/workflows/deploy.yml
- book.toml
Testing the new updated deployment action. This adds a "edit page" link on top of each page
> Edit page feature

- .github/workflows/deploy.yml
The latest mdbook release includes the "edit page" feature @flavio provided.
We don't need to build our own mdbook in order to publish our docs website.
> GH action: update to latest mdbook

- src/writing-policies/swift.md
A quick follow up about the latest work done on Swift policies:
* The SDK is now ready
* We have a template project for Swift policies
> Update Swift page

- src/quick-start.md
> Update documentation for the new CRD helm chart

- src/SUMMARY.md
- src/distributing-policies/oci-registries-support.md
Fixes: https://github.com/kubewarden/docs/issues/58
> Add information about supported OCI registries

- src/quick-start.md
Add AdmissionPolicy to the docs
Fix #89
> Add AdmissionPolicy documentation

- src/tasks.md
Fix https://github.com/kubewarden/docs/issues/98
Before: `kwctl manifest`
Now:    `kwctl scaffold manifest`
> docs: Update for `kwctl scaffold`

- src/SUMMARY.md
- src/writing-policies/spec/06-signature-verifier-policies.md
Fix https://github.com/kubewarden/docs/issues/108
Rendered: https://github.com/viccuad/docs/blob/spec-sigstore-verify/src/writing-policies/spec/06-signature-verifier-policies.md
`mdbook serve` locally.
> Add writing-policies/spec/06-signature-verifier-policies.md

- docs/introduction.md
and make it more welcoming / encouraging to give Kubewarden a try.
Signed-off-by: Klaus Kämpf <kkaempf@suse.de>
Fix #XXX
https://docs.kubewarden.io/
> Soften the initial warning message

- docusaurus.config.js
Adding google analytics tracking ID per request
> Updating Google Analytics tracking ID

- package.json
- yarn.lock
Update to 2.0.0-beta.21
This will solve some of the security issues reported by dependabot
> Update to latest release of docusaurus

- .github/workflows/test.yml
Attempt to build the website on PRs. This will spot common issues like broken links
> Add GitHub Action for testing

- docs/operator-manual/telemetry/tracing/01-quickstart.md
Install kubewarden-defaults in tracing docs
> Tracing docs update

- docs/writing-policies/go/01-intro-go.md
- docs/writing-policies/go/02-scaffold.md
- docs/writing-policies/go/03-policy-settings.md
- docs/writing-policies/go/04-validation.md
- docs/writing-policies/go/05-e2e-tests.md
- docs/writing-policies/go/09-validation-with-queries.md
- sidebars.js
Cover the usage of native Go types when writing validation policies.
To the ones reviewing it: it would be great if you could try to reproduce everything step-by-step to ensure the final code builds and runs as expected. :pray: 
I'll cover mutation policies later on, either updating this PR or by creating a new one
> Update the Go documents

- docs/operator-manual/telemetry/opentelemetry/01-quickstart.md
- docs/operator-manual/telemetry/tracing/01-quickstart.md
Fixes OpenTelemetry and Jaeger install instructions.
> Update opentelemetry & tracing install instructions

- package.json
- yarn.lock
Update to the latest stable release of it. We have been using RC releases so far.
> Docusaurus 2.0 has been released!

- docs/distributing-policies/secure-supply-chain.md
```
~ kubectl logs -n kubewarden policy-server-default-bf9dc996b-9z96j
Cannot create sigstore verification config: Not a valid configuration file: Err(Message("unknown field `annotation`, expected one of `owner`, `key`, `annotations`", None))
```
> Fix typo annotation -> annotations

- docs/operator-manual/policy-servers/02-private-registry.md
Expand Docker Config Secrets and private registry.
> docs: Expand Docker Config Secrets and private registry

- docs/operator-manual/telemetry/01-quickstart.md
- docs/operator-manual/telemetry/metrics/01-quickstart.md
- docs/operator-manual/telemetry/opentelemetry/01-quickstart.md
- docs/operator-manual/telemetry/tracing/01-quickstart.md
- sidebars.js
Relates to: https://github.com/kubewarden/kubewarden-controller/pull/304
Depends on: https://github.com/kubewarden/helm-charts/pull/136
Update OpenTelemetry story with the changes discovered in https://github.com/kubewarden/kubewarden-controller/pull/304.
Move to Helm charts for some components as their upstreams are in good shape now.
List Helm chart versions at time of writing for reproducibility.
Fix some values.yaml mistakes.
> Update OpenTelemetry story

- docs/quick-start.md
* Use stable versions of our CRDs
* Use latest versions of the policies being demoed
* Update some of the output that changed over the time
> fix: update quickstart references

- docs/tasksDir/pod-security-with-kubewarden.md
- sidebars.js
Adds a documentation showing how user can use Kubewarden together with the Pod Security Admission from Kubernetes.
Fix https://github.com/kubewarden/kubewarden-controller/issues/260
> Pod Security Admission.

- package.json
- yarn.lock
Update docusaurus and its dependencies.
> chore: update docusaurus

- docs/distributing-policies/oci-registries-support.md
Add quay and list of recommended cli tools
Tested `skopeo` usage.
> Add quay and list of recommended cli tools

- docs/distributing-policies/oci-registries-support.md
Verified by field contributors.
> Add min version for distribution

- docs/distributing-policies/oci-registries-support.md
> Expand OCI registries list

- docs/operator-manual/telemetry/tracing/01-quickstart.md
From https://github.com/kubewarden/kubewarden-controller/pull/304
Signed-off-by: Víctor Cuadrado Juan <vcuadradojuan@suse.de>
> List jaeger-operator version

- docs/security/verifying-kubewarden.md
> Update verification process for helm charts and policies

- docs/operator-manual/airgap/02-install.md
`kwctl` needs to be authenticated against the registry, just as `docker`.
Wrap command lines so it's more readable.
> Add reminder that kwctl needs to be authenticated

- docs/operator-manual/Rancher-Fleet.md
- sidebars.js
Relates to https://github.com/kubewarden/policy-server/issues/394.
Needs https://github.com/kubewarden/automation/pull/41
Explain how to use Rancher Fleet Bundles to codify Kubewarden dependencies.
> Add Rancher Fleet page

- docs/operator-manual/policy-evaluation-timeout.md
- sidebars.js
This fixes https://github.com/kubewarden/docs/issues/157
> feat: add docs about policy evaluation timeout feature

- docs/operator-manual/telemetry/opentelemetry/01-quickstart.md
- docs/tasksDir/mutating-policies.md
Fix [#403](https://github.com/kubewarden/kubewarden-controller/issues/403)
> Updated registry address from k8s.gcr.io to registry.k8s.io

- docs/distributing-policies/publish-policy-to-artifact-hub.md
> Revert "feat: Tell users about automationg for `artifacthub-pkg.yml`"

- docs/distributing-policies/publish-policy-to-artifact-hub.md
Relates to https://github.com/kubewarden/github-actions/pull/54.
Relates to https://github.com/kubewarden/github-actions/issues/48.
> Update artifacthub docs for our GHA v2

- package.json
- yarn.lock
Use latest version of docusaur
> chore(deps): update docusaur

- docs/distributing-policies/publish-policy-to-artifact-hub.md
Relates to https://github.com/kubewarden/kubewarden-controller/issues/389
> Update docs for GHA v3.1.0

- docs/writing-policies/spec/host-capabilities/02-signature-verifier-policies.md
- docs/writing-policies/spec/host-capabilities/03-container-registry.md
- docs/writing-policies/spec/host-capabilities/05-crypto.md
Fix Host Capabilities Specifications
Fix #181
> fix: host capabilities specifications

- docs/writing-policies/spec/05-context-aware-policies.mdx
> Expand context aware info

- package-lock.json
- package.json
- yarn.lock
Use latest stable release of docusaurus
> chore(deps): update docusaurus

- docs/introduction.md
And, also to check I'm doing the processes correctly.
Fix #XXX
> Some minor changes to refresh the introduction page.

- docs/distributing-policies.md
There are a few TODO to follow up.
> Distributing policies. A refresh of the language used.

- docs/explanations/opa-comparison.md
- sidebars.js
Summarize the main differences between OPA Gatekeeper and Kubewarden.
> Add OPA Gatekeeper comparison page

- docs/explanations/context-aware-policies.md
There is a question in a TODO: at the end of the page. Thanks.
> Refresh of context aware policies.

- docs/tasksDir/psp-migration.md
Partial rework. Better language. Requires completion and a note about AppVia.
> PSP migration. 

- docs/writing-policies/wasi.md
Remove some leftover plus some minor fixes.
> fix: improve plain WASI policies docs

- docs/tasksDir/pod-security-admission-with-kubewarden.md
There are some questions in TODOs.
Thanks.
> Refresh of Pod Security Admission.

- static/robots.txt
> Added a robots.txt

- docs/howtos/audit-scanner.md
Add policy reporter installation info, without air gap info.
see https://deploy-preview-238--silly-bunny-8cedd0.netlify.app/howtos/audit-scanner
> Add policy reporter installation info

- docs/distributing-policies/custom-certificate-authorities.md
> Refresh of custom cert authority docs.

- docs/architecture.md
First pass, just for language. Next up the diagrams, maybe.
Will close #248
> Refresh of architecture introduction document.

- sidebars.js
> fix: Remove duplicated entry for context-aware-policies

- docs/distributing-policies/oci-registries-support.md
Minor refresh/fixes/typos.
Will close #253 when complete.
> Refresh OCI registry support.

- docs/introduction.md
- docusaurus.config.js
- versioned_docs/version-1.7/introduction.md
- versioned_docs/version-1.8/introduction.md
Will close #270 if/when merged.
> Header and footer standardization efforts.

- docs/introduction.md
Will close #251 if/when merged.
I need a little more guidance for this one. From @viccuad . Thanks.
> KW is a PE not just a KDAC.

- docs/operator-manual/monitor-mode.md
> Refresh of the monitor mode description.

- docs/security/threat-model.md
Will close #254 when merged.
There is one TODO(my todo). I'm wondering all of these todos mentioned in the document (Kubewarden team todos) are still valid, and hence the associated mitigations..
Thanks.
> Refresh of the threat model documentation.

- docs/writing-policies/index.md
> Refresh of writing policies intro.

- package.json
- yarn.lock
> chore(deps): Update to latest version of docusarus

- docs/tasksDir/psp-migration.md
Updates the psp migration docs updating the output generated by the latest psp-migration script. As well as formatting some of text block to be under 80 columns.
Fix https://github.com/kubewarden/docs/issues/207
> fix: update docs using output of the latest psp-migration script.

- versioned_docs/version-1.8/operator-manual/telemetry/opentelemetry/01-quickstart.md
> Mention that openelemety should be HA in production

- docs/explanations/context-aware-policies.md
- docs/writing-policies/rego/01-intro-rego.md
- docs/writing-policies/spec/05-context-aware-policies.md
- versioned_docs/version-1.7/writing-policies/rego/01-intro-rego.md
Update the documentation to reflect the possibility to write context aware policies using Rego.
This is part of https://github.com/kubewarden/kubewarden-controller/issues/513
**Note for reviewers:** when looking at the preview site, make sure you switch to the "next" version of the documentation. Otherwise you will not see these changes :wink:
> Context aware policies can be written with Rego

- versioned_docs/version-1.7/tasksDir/psp-migration.md
- versioned_docs/version-1.8/tasksDir/psp-migration.md
Replicates the fixes in the latest PSP migration docs to the versioned docs.
> fix: PSP migration docs

- docs/howtos/raw-policies.md
> fix: Use correct image tag, set port-forward

- docs/quick-start.md
> chore: Point to artifacthub.io instead of hub.kubewarden.io

- docs/tasksDir/mutating-policies.md
Fix https://github.com/kubewarden/docs/issues/117
> Add danger note on mutating policies

- docs/operator-manual/upgrade-path.md
- docusaurus.config.js
- package.json
- sidebars.js
- yarn.lock
Fix https://github.com/kubewarden/docs/issues/286.
Adapted from
https://github.com/kubewarden/rfc/blob/main/rfc/0008-upgrade-statement.md
Once this is approved, I can manually add it to the `v1.9` docs for it to be live.
> feat: Add upgrade path reference docs

- docs/operator-manual/dependency-matrix.md
- docs/quick-start.md
- sidebars.js
Fix https://github.com/kubewarden/docs/issues/287
> Add dependency matrix page

- docs/writing-policies/rust/01-intro-rust.md
- docs/writing-policies/rust/02-create-policy.md
- docs/writing-policies/rust/03-define-policy-settings.md
- docs/writing-policies/rust/04-write-validation-logic.md
- docs/writing-policies/rust/05-mutation-policy.md
- docs/writing-policies/rust/06-logging.md
- docs/writing-policies/rust/07-build-and-distribute.md
In the third, 03-define-policy-settings, I am having trouble with the worked Rust examples. I need a little help. Thanks.
When complete and merged will close #294.
> Refresh of writing Rust policies.

- docs/operator-manual/telemetry/metrics/01-quickstart.md
Relates to https://github.com/kubewarden/policy-server/issues/601.
The link will work when new releases are available. That may be appVersion 1.9.1 for policy-server.
The same link works for my fork:
https://github.com/viccuad/policy-server/releases/latest/download/kubewarden-dashboard.json
> Point to GH release for grafana dashboard

- versioned_docs/version-1.7/operator-manual/telemetry/metrics/01-quickstart.md
- versioned_docs/version-1.8/operator-manual/telemetry/metrics/01-quickstart.md
- versioned_docs/version-1.9/operator-manual/telemetry/metrics/01-quickstart.md
Relates to https://github.com/kubewarden/policy-server/issues/601
> chore: version the grafana-dashboard links

- docs/operator-manual/policies.md
- sidebars.js
See https://deploy-preview-320--silly-bunny-8cedd0.netlify.app/next/operator-manual/policies
This will end at https://docs.kubewarden.io/next/operator-manual/policies when merged.
> feat: Add howto -> operator -> configuring policies

- docs/explanations/audit-scanner/audit-scanner.md
- versioned_docs/version-1.9/explanations/audit-scanner/audit-scanner.md
> fix: Audit scanner typo

- docs/contribution-guide/contributing.md
- docs/contribution-guide/suggesting-an-improvement.md
- docs/operator-manual/ui-extension/02-metrics.md
- docs/operator-manual/ui-extension/03-tracing.md
Also changed some language a little.
> Added front matter to the four files which had none at all.

- docs/distributing-policies/custom-certificate-authorities.md
- docs/distributing-policies/oci-registries-support.md
- docs/distributing-policies/publish-policy-to-artifact-hub.md
- docs/distributing-policies/secure-supply-chain.md
> Updated frontmatter for distributing policies

- docs/operator-manual/01-intro.md
- docs/operator-manual/airgap/01-requirements.md
- docs/operator-manual/airgap/02-install.md
- docs/operator-manual/policies.md
- docs/operator-manual/policy-evaluation-timeout.md
- docs/operator-manual/policy-servers/01-custom-cas.md
- docs/operator-manual/policy-servers/02-private-registry.md
- docs/operator-manual/telemetry/metrics/01-quickstart.md
- docs/operator-manual/telemetry/metrics/02-reference.md
- docs/operator-manual/telemetry/opentelemetry/01-quickstart.md
- docs/operator-manual/telemetry/tracing/01-quickstart.md
- docs/operator-manual/ui-extension/01-install.md
- docs/operator-manual/verification-config.md
> front matter update for ops manual

- docs/security/01-intro.md
- docs/security/disclosure.md
- docs/security/threat-model.md
- docs/security/verifying-kubewarden.md
> front matter updates for security section

- docs/writing-policies/rego/01-intro-rego.md
- docs/writing-policies/rego/02-builtin-support.md
- docs/writing-policies/rego/gatekeeper/01-intro.md
- docs/writing-policies/rego/gatekeeper/02-create-policy.md
- docs/writing-policies/rego/gatekeeper/03-build-and-run.md
- docs/writing-policies/rego/gatekeeper/04-distribute.md
- docs/writing-policies/rego/open-policy-agent/01-intro.md
- docs/writing-policies/rego/open-policy-agent/02-create-policy.md
- docs/writing-policies/rego/open-policy-agent/03-build-and-run.md
- docs/writing-policies/rego/open-policy-agent/04-distribute.md
- docs/writing-policies/rego/open-policy-agent/05-raw-policies.md
- docs/writing-policies/spec/01-intro-spec.md
- docs/writing-policies/spec/02-settings.md
- docs/writing-policies/spec/03-validating-policies.md
- docs/writing-policies/spec/04-mutating-policies.md
- docs/writing-policies/spec/05-context-aware-policies.md
- docs/writing-policies/spec/host-capabilities/01-intro-host-capabilities.md
- docs/writing-policies/spec/host-capabilities/02-signature-verifier-policies.md
- docs/writing-policies/spec/host-capabilities/03-container-registry.md
- docs/writing-policies/spec/host-capabilities/04-net.md
- docs/writing-policies/spec/host-capabilities/05-crypto.md
- docs/writing-policies/spec/host-capabilities/06-kubernetes.md
> Front matter updates, writing policies

- docs/tasksDir/mutating-policies.md
Fix https://github.com/kubewarden/docs/issues/335.
See https://deploy-preview-336--silly-bunny-8cedd0.netlify.app/next/tasksDir/mutating-policies.
> Add mutating policies danger explanations

- docs/writing-policies/spec/05-context-aware-policies.md
- docs/writing-policies/wasi/01-intro-wasi.md
Fix https://github.com/kubewarden/docs/issues/337
> Add mentions to WASI Go context-aware policies

- docs/howtos/audit-scanner.md
- docs/howtos/raw-policies.md
- docs/introduction.md
- docs/operator-manual/CRDs.md
- docs/operator-manual/dependency-matrix.md
- docs/operator-manual/upgrade-path.md
- docs/tasksDir/mutating-policies.md
- docs/writing-policies/rego/02-builtin-support.md
- docs/writing-policies/rego/open-policy-agent/01-intro.md
- docs/writing-policies/rust/08-raw-policies.md
- docs/writing-policies/spec/02-settings.md
- docs/writing-policies/spec/host-capabilities/03-container-registry.md
Too many L1 heading in some pages.
> Fix multi L1 headings

- versioned_docs/version-1.10/security/threat-model.md
Relates to https://github.com/kubewarden/kubewarden-controller/issues/379.
> Update threat-model.md for Kubewarden 1.10.0

- docs/reference/spec/01-intro-spec.md
- docs/reference/spec/02-settings.md
- docs/reference/spec/03-validating-policies.md
- docs/reference/spec/04-mutating-policies.md
- docs/reference/spec/05-context-aware-policies.md
- docs/reference/spec/host-capabilities/01-intro-host-capabilities.md
- docs/reference/spec/host-capabilities/02-signature-verifier-policies.md
- docs/reference/spec/host-capabilities/03-container-registry.md
- docs/reference/spec/host-capabilities/04-net.md
- docs/reference/spec/host-capabilities/05-crypto.md
- docs/reference/spec/host-capabilities/06-kubernetes.md
Update spec docs fm to be reference.
> Fix frontmatter in refdocs

- docs/reference/spec/05-context-aware-policies.md
Cover a change introduced by the next release of Kubewarden.
This is related with https://github.com/kubewarden/kubewarden-controller/issues/575
This is the direct link to the new section: https://deploy-preview-355--silly-bunny-8cedd0.netlify.app/next/writing-policies/spec/context-aware-policies#constraints
> Update context aware documentation

- docs/howtos/telemetry/30-metrics-qs.md
Add missing parameter if the namespaces doesn't already exist
(Docs)
> docs: add missing parameter

- docs/tutorials/testing-policies/02-policy-authors.md
- docs/tutorials/testing-policies/03-cluster-operators.md
- docs/tutorials/testing-policies/index.md
> Refresh tutorial on policy testing.

- docs/tutorials/writing-policies/rego/01-intro-rego.md
- docs/tutorials/writing-policies/rego/02-builtin-support.md
- docs/tutorials/writing-policies/rego/gatekeeper/01-intro.md
- docs/tutorials/writing-policies/rego/gatekeeper/02-create-policy.md
- docs/tutorials/writing-policies/rego/gatekeeper/03-build-and-run.md
- docs/tutorials/writing-policies/rego/gatekeeper/04-distribute.md
- docs/tutorials/writing-policies/rego/open-policy-agent/01-intro.md
- docs/tutorials/writing-policies/rego/open-policy-agent/02-create-policy.md
- docs/tutorials/writing-policies/rego/open-policy-agent/03-build-and-run.md
- docs/tutorials/writing-policies/rego/open-policy-agent/04-distribute.md
- docs/tutorials/writing-policies/rego/open-policy-agent/05-raw-policies.md
Will contribute to #204 when merged.
I have a question marked by a TODO: The intro refers to Datalog. Is this the same Datalog as referred to by the Wikipedia entry or something else? Answered, thanks.
> Refresh language for tutorial on Rego.

- docs/explanations/audit-scanner/policy-reports.md
Adds policy name and policy namespace to policy reports examples
> docs: update policy reports examples

- docs/explanations/audit-scanner/policy-reports.md
Add new label `kubewarden.io/policyreport-version: v2`.
Part of https://github.com/kubewarden/helm-charts/issues/408
> Update policyreports for 1.11

- docs/reference/CRDs.md
update generated PolicyServer CRD docs with limits and requests
> docs: update generated PolicyServer CRD docs with limits and requests

- src/css/custom.css
It keeps the original, fine Kubewarden logo.
Tries to use the SUSE color palette: https://codepen.io/andyfitz/live/LYqRmoQ/953da03319fd7e7c332ee071a260241b
Changes to both light and dark mode.
For your brief consideration.
Also, deleted a load of unused CSS stuff from times gone by.
> On-brand color experiment. 

- docs/howtos/telemetry/10-opentelemetry-qs.md
- docs/reference/dependency-matrix.md
Follow-up PR with otel version changes
> Update additional otel version mentions

- docusaurus.config.js
Note to self: Check that it's working after merge.
> Use the CNCF gtag for analytics

- docs/disclosure.md
Updates the disclosure.md to follow the most update disclosure procedure described in the community repository.
Related to https://github.com/kubewarden/kubewarden-controller/issues/727
> chore: update disclosure.md to follow community repo.

- docs/tutorials/writing-policies/CEL/01-intro-cel.md
- docs/tutorials/writing-policies/CEL/02-reusing-vap.md
- docs/tutorials/writing-policies/CEL/03-context-aware.md
- docs/tutorials/writing-policies/CEL/_category_.json
Part of https://github.com/kubewarden/cel-policy/issues/8.
> Add CEL intro and reusing VAP page

- docs/tutorials/writing-policies/CEL/04-example-sigstore.md
Relates to https://github.com/kubewarden/cel-policy/issues/8.
We may want until https://github.com/kubewarden/policy-evaluator/issues/521 is closed before merging.
> Add cel sigstore example

- docs/tutorials/writing-policies/CEL/01-intro-cel.md
- docs/tutorials/writing-policies/CEL/03-context-aware.md
Relates to https://github.com/kubewarden/cel-policy/issues/8
> Update cel context aware example

- docs/howtos/production-deployments.md
Adds a new HowTo documentation explaining how users can define tolerations and affinity configuration for the whole Kubewarden stack.
> feat: global toleration and affinity documentation.

- docs/reference/CRDs.md
- docs/tutorials/testing-policies/03-cluster-operators.md
- docs/tutorials/writing-policies/CEL/01-intro-cel.md
- docs/tutorials/writing-policies/CEL/02-reusing-vap.md
- docs/tutorials/writing-policies/CEL/03-context-aware.md
- docs/tutorials/writing-policies/CEL/04-example-sigstore.md
- docs/tutorials/writing-policies/go/01-intro-go.md
- docs/tutorials/writing-policies/go/02-scaffold.md
- docs/tutorials/writing-policies/go/03-policy-settings.md
- docs/tutorials/writing-policies/go/04-validation.md
- docs/tutorials/writing-policies/go/05-e2e-tests.md
- docs/tutorials/writing-policies/go/06-logging.md
- docs/tutorials/writing-policies/go/07-automate.md
- docs/tutorials/writing-policies/go/08-distribute.md
- docs/tutorials/writing-policies/go/09-validation-with-queries.md
- docs/tutorials/writing-policies/go/10-raw-policies.md
- docs/tutorials/writing-policies/metadata.md
- docs/tutorials/writing-policies/rust/01-intro-rust.md
- docs/tutorials/writing-policies/rust/02-create-policy.md
- docs/tutorials/writing-policies/rust/03-define-policy-settings.md
- docs/tutorials/writing-policies/rust/04-write-validation-logic.md
- docs/tutorials/writing-policies/rust/05-mutation-policy.md
- docs/tutorials/writing-policies/rust/06-logging.md
- docs/tutorials/writing-policies/rust/07-build-and-distribute.md
- docs/tutorials/writing-policies/rust/08-raw-policies.md
- docs/tutorials/writing-policies/wasi/01-intro-wasi.md
- docs/tutorials/writing-policies/wasi/02-raw-policies.md
Part of #400 
Better auto generation of learning paths.
> More accurate persona tagging in frontmatter.

- docs/reference/CRDs.md
Fix https://github.com/kubewarden/kubewarden-controller/issues/758
File taken from
kubewarden-controller/docs/crds/CRD-docs-for-docs-repo.md
> feat: Update reference/CRDs.md for matchConditions

- docs/explanations/comparisons/opa-comparison.md
Refresh OPA Gatekeeper comparison with CEL.
> Refresh OPA Gatekeeper comparison with CEL

- docs/disclosure.md
Relates to https://github.com/kubewarden/community/issues/12
> Expand security disclosure

- docs/tutorials/writing-policies/go/05-e2e-tests.md
Relates to
https://github.com/kubewarden/kubewarden-controller/issues/838.
> fix: We don't expect kwctl to output a json anymore

- docs/tutorials/writing-policies/CEL/02-reusing-vap.md
- versioned_docs/version-1.16/tutorials/writing-policies/CEL/02-reusing-vap.md
Clarification, matchConditions is already implemented.
> matchConditions is already implemented

- docs/reference/CRDs.md
Adds reference documentation for the new policy group types: ClusterAdmissionPolicyGroup and AdmissionPolicyGroup
Fix #447
> feat(docs): Policy Groups CRDs reference documentation.

- docs/howtos/policy-groups.md
Adds a new Howto page showing how to use the policy groups.
Fix #449
> feat(docs): howto use policy groups.

- docs/explanations/policy-groups.md
- docs/howtos/policy-groups.md
Consume latest version of the policy
> chore: update trusted-repo-version

- docs/tutorials/verifying-kubewarden.md
Relates to https://github.com/kubewarden/kubewarden-controller/issues/856.
Tested commands locally by hand.
> Explain different attestations and add missing info for kwctl

- docs/howtos/airgap/02-install.md
- docs/reference/artifacts.md
Recent PR #472 needs a few minor tweaks. Thanks.
> A few minor corrections to PR#472.

- docs/reference/oci-registries-support.md
> Update OCI artifacts link in oci-registries-support.md

- docs/howtos/telemetry/10-opentelemetry-qs.md
- docs/howtos/telemetry/20-tracing-qs.md
- docs/howtos/telemetry/30-metrics-qs.md
- docs/howtos/telemetry/40-custom-otel-collector.md
> Some language improvements and better active voice for OTEL collector.

- docs/howtos/raw-policies.md
Part of  https://github.com/kubewarden/policy-server/issues/906
> Change `url` to `module` for policy-server >= 1.21

- docs/organization.md
- docs/personas.md
> Organisation & Personas page.

- .github/workflows/update-ref-docs.yml
- updatecli/update-cli-ref-docs.yaml
- updatecli/updatecli.d/headers.yaml
- updatecli/values.d/headers.yaml
- updatecli/values.d/update-cli-ref-docs.yaml
Updates CI job used to copy CLI reference documentation to add the missing "Signed-off-by" directives to make DCO bot happy. Also update the updatecli policy used to allow the same customization.
> fix: add missing Signed-off-by.

- .github/workflows/update-ref-docs.yml
Updates the CI job to run it twice a week. It will run at 00:00 on Mondays and Wednesdays.
> fix(ci): run CI to update CLI reference docs twice a week.

- docs/reference/artifacts.md
- docs/tutorials/verifying-kubewarden.md
Updates for verification to include detail from blog posts/release notes.
Fixes #490 when complete.
> Updates to verification of Kubewarden for issue #490

- docusaurus.config.js
Update docs based on https://github.com/kubewarden/community/issues/33
> Move from X to Bluesky & Mastodon

- docusaurus.config.js
Fix based on https://github.com/kubewarden/kubewarden.io/pull/300#discussion_r1930165878
> Fix Bluesky url

- docs/howtos/argocd-installation.md
Adds a documentation page explaining how to install the Kubewarden stack with ArgoCD application CRDs.
Fix https://github.com/kubewarden/kubewarden-controller/issues/980
> feat: how to install Kubewarden with ArgoCD.

- docs/reference/CRDs.md
Reflect the changes done as part of the 1.21 release to the `ClusterAdmissionGroupPolicy` and to the `AdmissionPolicyGroup` CRDs
> fix: update CRDs

- .github/workflows/updatecli.yml
Commits on Jan 30, 2025
[fix: Correctly use --file flag on updatecli compose](https://github.com/kubewarden/docs/commit/c20208f76fa31f3a4e35bbe437553454ae66f956)
Tested locally.
Also tested by @jvanz: https://github.com/jvanz/docs/actions/runs/13052874410
> Fix Updatecli Dependency Management workflow runs

- updatecli/updatecli-compose.yaml
Updates updatecli policy to use the right file path to update the compose file used in the updatecli.yml workflow.
Fix #536
> fix(ci): update updatecli policy.

- docs/disclosure.md
- docs/introduction.md
- docs/personas.md
- docs/quick-start.md
> CNCF recommendations - Introductory pages review for active voice, language and some formatting.

- docs/reference/monitor-mode.md
> CNCF active language review for monitor mode.

- docs/reference/threat-model.md
> CNCF active language review for threat model.

- docs/introduction.md
Part of the work on https://github.com/kubewarden/community/issues/36
> Enhance vendor neutrality statement.

- docs/reference/threat-model.md
Fix https://github.com/kubewarden/kubewarden-controller/issues/1034.
> Update threat model with mTLS changes

- docs/howtos/security-hardening/secure-supply-chain.md
> Fixed GH actions link in `secure-supply-chain.md`

- docs/howtos/security-hardening/webhook-mtls.md
Incorporate feedback from @pjbgf:
- Increase the expiration time of the root CA and the client certificate
issued by that
- Provide a simple openSSL configuration when creating the root CA and
the client certificate
- Increase the RSA key size
- Fix a typo about the location of the `admission.yaml` file
Thanks to @pjbgf for his review!
> fix: mtls howto

- docs/howtos/emergency-disable.md
Document how to temporarily disable Kubewarden.
Fixes https://github.com/kubewarden/docs/issues/586
> docs: add howto about emergency disable

- netlify.toml
Netlify builds are failing. Increasing resources for node may help.
> This may fix the build problems for Netlify (maybe).

- docs/use-cases.md
Relates to https://github.com/kubewarden/community/issues/11.
> docs: Add use-cases page

- docs/quick-start.md
CNCF recommends active rather than passive voice. Some other minor language improvements.
> More active voice language in quick start.

- docs/howtos/policy-servers/03-production-deployments.md
- docs/howtos/production-deployments.md
Fix https://github.com/kubewarden/docs/issues/599
Reorganized a bit the production deployments page.
CI, render
> docs: Add PriorityClass feature to production pages

- docs/use-cases.md
Ad non-goals to use cases page.
Fixes #602
> docs: add non-goals to use case page

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- .github/workflows/update-ref-docs.yml
- .github/workflows/updatecli.yml
Part of https://github.com/kubewarden/policy-sdk-dotnet/pull/55
> ci: Pin github-actions

- docs/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.10/security/verifying-kubewarden.md
- versioned_docs/version-1.11/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.12/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.13/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.14/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.15/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.16/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.17/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.18/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.19/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.20/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.21/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.22/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.23/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.24/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.25/tutorials/verifying-kubewarden.md
- versioned_docs/version-1.7/security/verifying-kubewarden.md
- versioned_docs/version-1.8/security/verifying-kubewarden.md
- versioned_docs/version-1.9/security/verifying-kubewarden.md
> fix Broken cosign blob signing link.

- docs/howtos/policies.md
> Update policy tags in hotwos/policies.md

- docs/reference/spec/host-capabilities/02-signature-verifier-policies.md
- docs/reference/spec/host-capabilities/06-kubernetes.md
> docs: add caching notes for signature verifier and kubernetes capabilities

- docs/reference/verification-config.md
For active voice and other things  as part of the CNCF recommendations.
As part of #477.
> Verification configuration language review 

- docs/reference/sources_yaml.md
> sources.yaml language refinement for CNCF.

- docs/reference/spec/02-settings.md
- docs/reference/spec/03-validating-policies.md
- docs/reference/spec/04-mutating-policies.md
- docs/reference/spec/05-context-aware-policies.md
>  Specification reference language improvements for CNCF.

- docs/howtos/raw-policies.md
- versioned_docs/version-1.26/howtos/raw-policies.md
Hey, I noticed that some of the docs are outdated when trying out the docs. 
I also added a small section for Mac users as it's easier to use a bind mount than a docker volume.
> Update tutorial for using raw-policies

- docs/reference/spec/host-capabilities/01-intro-host-capabilities.md
- docs/reference/spec/host-capabilities/02-signature-verifier-policies.md
- docs/reference/spec/host-capabilities/03-container-registry.md
- docs/reference/spec/host-capabilities/04-net.md
- docs/reference/spec/host-capabilities/05-crypto.md
- docs/reference/spec/host-capabilities/06-kubernetes.md
Active voice where possible. A few other tweaks. Part of work on #477.
> Reference/spec/host capabilities language review as per CNCF guidance.

- docs/reference/security-hardening/webhooks-hardening.md
> webhook hardening language improvements as per CNCF suggestions.

- docs/howtos/airgap/03-hauler.md
Adds a howto page explaining how users can use Hauler to help in the Kubewarden installation in a air gap environment.
Fix https://github.com/kubewarden/docs/issues/653
> feat(hauler): air gap installation with Hauler.

- docs/howtos/airgap/02-install.md
Also standardized use of air gap and air-gapped.
> Airgap howto. CNCF suggested language improvements.

- docs/howtos/policies.md
> Add section for the PolicyGroup negation pattern
