- src/quick-start.md
Some stuff got broken during the chimera -> kubewarden rename process.
This is required to fix issue #17
> Fix quickstart instructions

- src/SUMMARY.md
- src/writing-policies/rust.md
Restore the section, this time with up-to-date contents
> Add back the section about writing policies in Rust

- src/SUMMARY.md
- src/testing-policies/01-intro.md
- src/testing-policies/02-policy-authors.md
- src/testing-policies/03-cluster-operators.md
- src/writing-policies/go/05-e2e-tests.md
Split the testing document into two dedicated chapters.
Also, shuffle the topics around inside of the SUMMARY
This fixes #21
> Split "testing policies" section

- src/writing-policies/rust/02-create-policy.md
cargo generate is not part of a default rust installation so I have attempted to explain how to install the required tool
> Explain that cargo generate must be installed

- src/distributing-policies.md
- src/testing-policies/02-policy-authors.md
- src/testing-policies/03-cluster-operators.md
- src/writing-policies/go/03-policy-settings.md
- src/writing-policies/go/04-validation.md
- src/writing-policies/go/05-e2e-tests.md
- src/writing-policies/rust/03-define-policy-settings.md
- src/writing-policies/rust/06-build-and-distribute.md
- src/writing-policies/spec/01-intro.md
- Replace `policy-testdrive` with `kwctl` and adapt their command
names, arguments, workflow...
- Replace `wasm-to-oci` with `kwctl`
- Update the go project template so it includes some expected labels
to execute when following this documentation
- Make sure that all examples work as expected
Fixes: https://github.com/kubewarden/kubewarden.io/issues/15
> Adapt documentation

- src/quick-start.md
The release is installed in the `kubewarden` namespace, thus you have to specify it for uninstallation too.
> helm install --namespace kubewarden --create-namespace kubewarden-controller kubewarden/kubewarden-controller
> Add the namespace to the uninstall command

- src/writing-policies/rego/gatekeeper/02-create-policy.md
Point users to the GitHub template repository they can use to quickly port existing Gatekeeper policies to Kubewarden.
> Gatekeeper: add link to template repo

- book.toml
- src/SUMMARY.md
- src/distributing-policies/custom-certificate-authorities.md
- src/operator-manual/policy-servers/01-custom-cas.md
Update distributing-policies/custom-certificate-authorities.md with new
sources.yml format.
Add new operator-manual/policy-servers/01-custom-cas.md with info on
`spec.{sourceAuthorities,insecureSources}`.
Rename authors to Kubewarden Developers.
Fixes https://github.com/kubewarden/docs/issues/62.
> Update info on custom CAs, add operator page

- src/quick-start.md
Fixes: https://github.com/kubewarden/docs/issues/61
For the quick start there is no need to add any integration with
Jaeger or OpenTelemetry.
> quickstart: remove jaeger mention

- src/operator-manual/telemetry/metrics/01-quickstart.md
The flag to enable telemetry has been moved out from the policyserver field. Thus, it enables telemetry in the controller as well. This commit updates the docs to reflect that change in the chart values changes.
Closes #71
> Move telemetry flag in the chart values.

- src/distributing-policies/custom-certificate-authorities.md
Fixes https://github.com/kubewarden/kwctl/issues/144
I just tested on Linux. I took the [official documentation](https://docs.rs/directories/3.0.2/directories/struct.ProjectDirs.html#method.config_dir) as a base to calculate the path for Windows and Mac. For the [parameters](https://docs.rs/directories/3.0.2/directories/struct.ProjectDirs.html#parameters) we are using `io.kubewarden` as `qualifier` and `kubewarden` as `application`
> sources.yaml default path for kwctl

- src/SUMMARY.md
- src/mutating-policies.md
Created the mutating policies validation page, based on the new Kubewarden controller and policy server versions.
Updated the Summary page to add it as a follow-up to the tasks page
> New mutating policies page

- src/quick-start.md
Use `PolicyServer` instead of `Policy Server`, to match the Kubernetes resource name.
> quickstart: Use `PolicyServer` instead of `Policy Server`

- src/quick-start.md
Updates the quick start section explaining to the users how to install the kubewarden-controller and kubewarden-defaults charts if the user already have a Policy Server installed by older versions of the kubewarden-controller chart.
Fix #96 
I'm not sure if the current text is enough and if it is in the right place. Please, let me know how can I improve it.
> Documentation about the new kubewarden-defaults chart.

- src/writing-policies/javascript.md
Adds a tiny stub page on writing policies in JavaScript using [Javy](https://github.com/Shopify/javy)
- similar to the TypeScript stub page that just briefly mentions AssemblyScript
- minus the example
- I found out about Javy recently, think it might deserve a mention
- especially for potential eventual compatibility with [jsPolicy](https://github.com/loft-sh/jspolicy)
policies, similar to how Kubewarden has some Rego/OPA/Gatekeeper compat
N/A
It's a stub, so not particularly useful and potentially even misleading, but it also shows potential users that there is opportunity for JS usage as well. Javy is also in beta, so could be abandoned, but it is also used by Shopify, so maybe not so likely. The stub is also transparent …
> feat: add a tiny stub page on JavaScript policies

- src/writing-policies/typescript.md
Fixes a few typos, misspellings, and grammar in the TS doc
- duplicated "currently"
- misspelled "bacause" -> "because"
- misspelled "deserilize" -> "deserialize"
- lowercase serialize and deserialize as they aren't proper nouns; uppercase Classes as Class is a proper noun/term
- grammar: "Worth of note" -> "Worth noting"
- grammar: "a OCI" -> "an OCI"
N/A
Saw some small issues in the docs while I was reading them, figured I'd make some quick patches
N/A
Easier to read/understand/interpret docs
> fix: typos and grammar in TypeScript docs

- src/SUMMARY.md
- src/psp-migration.md
Adds a how-to guide explaining how users can migrate their Kubernetes PSPs to Kuberwarden policies.
Fix #88
> PSP migration guide.

- docs/quick-start.md
Updates the Quick Start guide changing the default PolicyServer version and warning the user about the `serviceAccountName` which can cause the deployment to fail.
> Warns user about policy server version and the `sa` field.

- docs/security/01-intro.md
- docs/security/disclosure.md
- docs/security/threat-model.md
- docs/security/verifying-kubewarden.md
- sidebars.js
This adds a new "Security" section, containing:
- Threat model: straight from the RFC.
- Verifying Kubewarden: info on how to verify Helm charts, containers, kwctl.
- Disclosure: info on how to disclose security vulns to us.
https://github.com/viccuad/docs/blob/add-security/docs/security/threat-model.md
https://github.com/viccuad/docs/blob/add-security/docs/security/verifying-kubewarden.md
https://github.com/viccuad/docs/blob/add-security/docs/security/disclosure.md
Tested locally with `yarn start`.
> feat: Add security/{threat, disclosure, verifying}

- docs/distributing-policies/oci-registries-support.md
- docs/operator-manual/telemetry/metrics/01-quickstart.md
- docs/operator-manual/telemetry/metrics/02-reference.md
- docs/operator-manual/telemetry/tracing/01-quickstart.md
- docs/quick-start.md
- docs/writing-policies/rego/01-intro-rego.md
- docs/writing-policies/rego/gatekeeper/01-intro.md
- docs/writing-policies/rego/gatekeeper/02-create-policy.md
- docs/writing-policies/rego/open-policy-agent/01-intro.md
- docs/writing-policies/rego/open-policy-agent/02-create-policy.md
- docs/writing-policies/spec/01-intro-spec.md
- docs/writing-policies/spec/02-settings.md
- docs/writing-policies/spec/04-mutating-policies.md
- docs/writing-policies/swift.md
Make use of [docusaurus admonitions](https://docusaurus.io/docs/markdown-features/admonitions) to give nuances to the docs.
The biggest changes have been done to the quickstart page, which now looks like that
> Make use of docusaurus admonitions

- docs/introduction.md
Removes admonition in the introduction page telling users that Kubewarden is in development. The project already released v1.0.0. Therefore, this sentence does not make sense.
> Remove admonition about development stage.

- docs/writing-policies/spec/host-capabilities/02-signature-verifier-policies.md
Fix https://github.com/kubewarden/policy-sdk-rust/issues/40
Fix https://github.com/kubewarden/policy-sdk-rust/issues/41
Locally. See also on the automated build.
> feat: Add the 2 new supported `v2/verify` payloads

- docs/distributing-policies/publish-policy-to-artifact-hub.md
- sidebars.js
Explain how anybody can publish their own policies to Artifact Hub.
Part of https://github.com/kubewarden/policy-hub/issues/190 epic.
> Add "publish to Artifact Hub" page

- docs/operator-manual/policy-servers/02-private-registry.md
- sidebars.js
Adds a new doc page explaining how Policy Servers can be configured to download policies from private registries.
Fix #113
> Docs about how to use private registry.

- docs/distributing-policies/oci-registries-support.md
Tested Harbor by using their demo server: https://goharbor.io/docs/2.6.0/install-config/demo-server/ and pushing and pulling a Kubewarden policy there: https://demo.goharbor.io/harbor/projects/11/repositories/pod-privileged/artifacts-tab
> Add Harbor to list of OCI registries

- docs/operator-manual/telemetry/metrics/01-quickstart.md
Install `kubewarden-defaults` chart in metrics docs, or we don't have a default PolicyServer.
> Install `kubewarden-defaults` chart in metrics docs

- docs/operator-manual/airgap/01-install.md
- docs/operator-manual/airgap/01-requirements.md
- docs/operator-manual/airgap/02-install.md
- sidebars.js
`common.cattle.systemDefaultRegistry` is still not available until we release the helm charts. Please use `image.repository` for now in the last step when installing with helm.
How to test this PR?
Private local registry is needed. You can create one with:
```
docker run -d -p 5000:5000 --restart=always --name registry registry:2
```
You can reach your registry at `localhost:5000`. You need kubernetes and policy-server to be able to pull from your registry. 
If you are using minikube you can make kubernetes to pull from localhost by forwarding with:
```
ssh -i $(minikube ssh-key) docker@$(minikube ip) -R 5000:localhost:5000
```
Then you can use `host.minikube.internal` for pulling policies. Example:
```
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
name: …
```
> feat: Add airgap docs

- docs/operator-manual/monitor-mode.md
- docs/operator-manual/policy-servers/01-custom-cas.md
- sidebars.js
These are tiny improvements of the the "Operator Manual" section of the sidebar.
Prior to this commit, certain entries had a double nested menu.
For example:
```
Operator Manual
\
`- Rancher Fleet
\
`- Rancher Fleet (THE ACTUAL DOC IS SHOWN ONCE THIS IS CLICKED)
```
This applied to other pages as well, making the whole navigation experience a bit cumbersome (too many clicks).
The new sidebar removes this kind of nesting:
```
Operator Manual
\
`- Rancher Fleet (THE ACTUAL DOC IS SHOWN ONCE THIS IS CLICKED)
```
Use a shorter name for the documentation about how to use custom CAs with Policy Server.
Apparently we though about writing multiple documents about the monitor     mode, but we never did. Because of that we had a dedicated folder with     just one single markdown file called …
> Small reorg of "Operator Manual" sidebar menu

- docs/distributing-policies/publish-policy-to-artifact-hub.md
Relates to https://github.com/kubewarden/kubewarden-controller/issues/389.
Tell users to execute `make artifacthub-pkg.yml`.
Tell users to activate checking of the file via the GHA workflow.
Tested in https://github.com/kubewarden/verify-image-signatures/pull/62.
> feat: Tell users about automationg for `artifacthub-pkg.yml`

- docs/distributing-policies/publish-policy-to-artifact-hub.md
Relates to https://github.com/kubewarden/kubewarden-controller/issues/389.
Tell users to execute `make artifacthub-pkg.yml`.
Tell users to activate checking of the file via the GHA workflow.
Tested in https://github.com/kubewarden/verify-image-signatures/pull/62.
> feat: Tell users about automationg for artifacthub-pkg.yml

- docs/quick-start.md
Ensure the kubewarden helm repo is always refreshed. If a user has already the repository added, he might end up installing an older version of kubewarden.
> fix: extend quickstart instructions

- docs/quick-start.md
Fix a typo in the Helm command used to refresh the Kubewarden repository
Fixing a typo that I've missed in #179
> Fix helm command typo

- docs/operator-manual/telemetry/metrics/01-quickstart.md
- docs/operator-manual/telemetry/opentelemetry/01-quickstart.md
- docs/operator-manual/telemetry/tracing/01-quickstart.md
Updates the telemetry documentation to reflect the latest changes in the controller where is not necessary to enable telemetry in the policy servers. Now the user just need to enable telemetry on the controller and it will configure policy server to has telemetry as well.
Related to https://github.com/kubewarden/kubewarden-controller/pull/442
> fix: telemetry is enabled only in the controller.

- .github/workflows/deploy.yml
- .github/workflows/test.yml
The following warning is found in the Summary tab of each run of an action using Node.js 12. E.g. https://github.com/kubewarden/docs/actions/runs/4956919089.
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Bump deprecated Node.js actions

- docs/writing-policies/spec/05-context-aware-policies.mdx
It seems that AdmissionPolicies lack `spec.ContextAwareResources`. Remove the notion to it in docs.
> Remove AdmissionPolicies from context aware docs

- docs/operator-manual/airgap/02-install.md
Updates the Air gap installation documentation adding the new configuration field in the kubewarden-defaults Helm chart used to define the default registry used by the recommended policies.
Related to https://github.com/kubewarden/helm-charts/issues/242
> feat: recommended policies default registry.

- docs/writing-policies/wasi.md
- sidebars.js
> Note: This policy is based on https://github.com/kubewarden/docs/pull/194
Explain how and when to write a plain WASI policy
TODO: create a template repository that contains a Go-based WASI policy and link it inside of the docs
> wasi policy

- docs/writing-policies/rego/gatekeeper/04-distribute.md
It seems that `kwctl manifest` is no longer a valid command and from what I could tell, we should use instead `kwctl scaffold manifest`
https://deploy-preview-197--silly-bunny-8cedd0.netlify.app/writing-policies/rego/gatekeeper/distribute#deploying-on-kubernetes
> Fixes Gatekeeper distribute example command

- docs/testing-policies/01-intro.md
- docs/testing-policies/02-policy-authors.md
- docs/testing-policies/03-cluster-operators.md
- sidebars.js
Part one, restructure and move to be immediately after 'Writing policies'. More logical placing than under Explanations.
> Testing policies. Review and refresh.

- docs/operator-manual/telemetry/metrics/01-quickstart.md
- docs/operator-manual/telemetry/opentelemetry/01-quickstart.md
- docs/operator-manual/telemetry/tracing/01-quickstart.md
Update the telemetry guide with the latest chart version, 
Add Kubewarden controller Prometheus configuration that was missing even if we were referring to metrics exported by the controller in the guide.
> docs: update telemetry guide

- docs/explanations/audit-scanner/limitations.md
Provide more details about the `*` symbol and its limitations.
> Clarify limitations of audit-scanner

- src/css/custom.css
The default fonts work better together, especially the code font.
> Revert to default fonts.

- .gitmodules
Remove uninitialized Git submodule.
My feeling is that this submodule was just added manually instead of running `git submodule add https://github.com/kubewarden/docs/blob/main/.gitmodules themes/projects-theme`
The problem that I am facing is while working on an update policy for this repository, Updatecli fails cloning this repository because it doesn't know how to clone the submodule
While running command such as `git submodule status`, I see nothing neither so 🤷🏾 
Current theme shouldn't be affected by removing this file so the preview environment should look like exactly [kubewarden](https://docs.kubewarden.io/).
> remove uninitialized git submodule

- .github/workflows/updatecli.yml
- update-compose.yaml
This pull request adds a new GitHub action workflow that execute Updatecli every hours.
At the moment we execute only one Updatecli policy defined on  [olblak/updatecli-policy-docusaurus](https://github.com/olblak/updatecli-policy-docusaurus)
```shell
export GITHUB_ACTOR="your GitHub username"
export GITHUB_TOKEN="your GitHub PAT"
updatecli compose diff --experimental
```
<details><summary>Local command execution</summary>
```
Experimental Mode Enabled
Pulling Updatecli policy "ghcr.io/olblak/policies/rancher/docusaurus/kubewarden:latest"
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "/tmp/updatecli/store/d1df02c09193500c8b2497c9ff2ce046f5eac2420f941e6c3c2a35b073cea431/updatecli.d/docusaurus.yaml"
SCM repository …
```
> chore: automate docusaurus versioning based on published Kubewarden version

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Node 16 is out of maintenance.
Let's hope that the website still build :) 
/
/
> deps: update nodejs to 20.x in GitHub action workflow

- .github/workflows/updatecli.yml
I thought the GITHUB_TOKEN was already available by default....
> Configure GITHUB_TOKEN for Updatecli workflow

- update-compose.yaml
The policy version 0.0.5 allows to automate its own versioning update.
<details>
```
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "policy/updatecli.d/update-compose-policy.yaml"
SCM repository retrieved: 1
++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++
++++++++++++
+ PIPELINE +
++++++++++++
#######################################
#######################################
SOURCES
=======
tag
---
Searching for version matching pattern "latest"
✔ Docker Image Tag "0.0.5" found matching pattern "latest"
digest
------
✔ Docker Image Tag ghcr.io/olblak/policies/rancher/docusaurus/kubewarden:0.0.5 resolved to digest ghcr.io/olblak/policies/rancher/docusaurus/kubewarden:0.0.5@sha256:81488900553174be2348b859f88f35c6ff0a6cab7342d8d4142bfec372fddb95
TARGETS
========
compose
------- …
```
> Update update-compose.yaml with docusaurus policy to 0.0.5

- docs/howtos/raw-policies.md
- docs/writing-policies/go/10-raw-policies.md
- docs/writing-policies/metadata.md
- docs/writing-policies/rego/open-policy-agent/05-raw-policies.md
- docs/writing-policies/rust/08-raw-policies.md
- docs/writing-policies/spec/03-validating-policies.md
- docs/writing-policies/wasi/01-intro-wasi.md
- docs/writing-policies/wasi/02-raw-policies.md
- sidebars.js
Adds raw policies documentation
TODO:
> docs: add raw policies documentation

- docs/writing-policies/spec/host-capabilities/03-container-registry.md
Adds new section in the container registry capabilities showing how users can fetch OCI image index to get information about OCI manifests in different platforms.
Fix #346
> feat: new OCI image index capability.

- docs/writing-policies/spec/host-capabilities/03-container-registry.md
Updates the waPC function name used to fetch OCI image manifest.
The new name is a review request from the policy-evaluator [PR](https://github.com/kubewarden/policy-evaluator/pull/429)
> chore: update capability name to fetch OCI image manifest.

- docs/quick-start.md
- versioned_docs/version-1.10/quick-start.md
Upstream docs don't wait via `kubectl wait` anymore (see [here](https://cert-manager.io/docs/installation/kubectl/)), and we know that installing via Helm waits correctly. We are also testing the cert-manager installation via helm, too.
Already tested via E2E tests.
> Install cert-manager via Helm in quickstart

- docs/reference/spec/host-capabilities/02-signature-verifier-policies.md
- docs/reference/spec/host-capabilities/03-container-registry.md
- docs/reference/spec/host-capabilities/04-net.md
- docs/reference/spec/host-capabilities/05-crypto.md
- docs/reference/spec/host-capabilities/06-kubernetes.md
Closes #374.
I had noticed that the host-capabilities pages in policy specification reference used tables for layout. Due to the fixed width content, these tables required a lot of horizontal scrolling and appear to be quite ugly.
Maybe something like this approach is better? As developers, which would you prefer? 
I've used sections, rather than tables, and put the code parts in expandable details. Unfortunately, Ctrl-f doesn't work on strings inside unexpanded details sections, so that's not great.
When we have decided on an approach (or decide to keep the current layout), I'll do the rest of the files in this section that have similar layout.
So, experimental, draft PR. Preferences?
New page: https://deploy-preview-375--silly-bunny-8cedd0.netlify.app/next/reference/spec/host-capabilitie …
> A better layout than tables in spec/host-capabilities 

- docs/howtos/telemetry/10-opentelemetry-qs.md
Latest [open-telemetry chart](https://github.com/open-telemetry/opentelemetry-helm-charts/releases/tag/opentelemetry-operator-0.56.0) requires collector image be set. Change is described in [their documentation](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/UPGRADING.md#0553-to-0560).
We have 2 options. I tried both and only `collector-contrib` works with our current setup.
- `otel/opentelemetry-collector-k8s`
- `otel/opentelemetry-collector-contrib`
> Open telemetry chart requires image repo

- docusaurus.config.js
- netlify.toml
Customizes the Netlify build used to preview the website building in development mode to disable the Google analytics. Therefore, we do not pollute our dashboard with development data.
Fix https://github.com/kubewarden/kubewarden.io/issues/224
> fix: disable Google analytics when building on Netlify.

- .gitignore
- docs/glossary.md
- docs/quick-start.md
- docusaurus.config.js
- js-lib/current-version.js
- js-lib/docusaurus-variables.js
- src/css/custom.css
- variables.json
docusaurus.config.js defines a preprocessor which replaces all instances of the variables defined in `./variables.json` with their values. See the changes in quick-start.md for an example. `[[< policy-server-component >]]' to 'PolicyServer'.
Part of #394.
> Infrastructure for implementing a Kubewarden controlled vocabulary.

- docs/howtos/audit-scanner.md
In the audit scanner the ingress configuration provided enabled the ingress to the policy-reporter service not for its UI. As stated in the documentation. This commit fix that by updating the example ingress configuration enabling the UI one.
Fix https://github.com/kubewarden/helm-charts/issues/463
> fix: enable right policy-reporter UI ingress.

- docs/howtos/audit-scanner.md
- docusaurus.config.js
Explain how to trigger a manual run of the audit-scanner, to not wait 60 minutes for the next run.
Prior to this commit, this document was called "audit-scanner installation howto". Since the document is no longer about "installation", the title has been changed to reflect that.
The change is visible only under the "next" version of the docs. [This](https://deploy-preview-413--silly-bunny-8cedd0.netlify.app/next/howtos/audit-scanner) is a link to the updated howto.
As you notice, the sidebar element is now called just "Audit Scanner"
> audit-scanner howto: add more instruction

- docs/howtos/vap-migration.md
- docs/tutorials/writing-policies/CEL/02-reusing-vap.md
This addresses https://github.com/kubewarden/docs/issues/418
The changes are visible in the "next" branch.
These are the links to the live preview:
* [howto page](https://deploy-preview-419--silly-bunny-8cedd0.netlify.app/next/howtos/vap-migration)
* [New tip box](https://deploy-preview-419--silly-bunny-8cedd0.netlify.app/next/tutorials/writing-policies/CEL/reusing-vap#yet-to-be-implemented-equivalences): scroll a little up to see the new box
> Document how to migrate from VAP to KW

- docs/quick-start.md
Adds an embedded HTML with the policies available in the ArtifactHub
Fix #401
> feat: policies list in the quick start page.

- docs/howtos/airgap/02-install.md
- docs/howtos/telemetry/10-opentelemetry-qs.md
- docs/quick-start.md
v1.13 is out of support, see https://cert-manager.io/docs/releases/.
PR also fixes installation warning: 
```
⚠️  WARNING: `installCRDs` is deprecated, use `crds.enabled` instead.
```
> Update cert manager to supported v1.15

- docs/reference/sources_yaml.md
> Clarify the sources usage on PolicyServer CRs

- variables.json
Fix correct var name for `admission-policy`, if not it shows as AdmissionServer (e.g: in [quickstart](https://docs.kubewarden.io/quick-start#admissionpolicy)).
> fix: Use correct var substitution for admission-policy

- docs/disclosure.md
Fix missing link introduced with https://github.com/kubewarden/docs/pull/437.
> fix: Add missing slack-room link

- docusaurus.config.js
Here: 
https://forums.rancher.com/t/rancher-release-v2-8-2/42526#opa-gatekeeper-mapps-42
And probably other places in Rancher notes and docs there is a link to 
https://docs.kubewarden.io/explanations/opa-comparison
which needs to be redirected to the new location
https://docs.kubewarden.io/explanations/comparisons/opa-comparison
> Redirect for OPA comparison, old link used in Rancher docs

- docs/reference/spec/host-capabilities/06-kubernetes.md
- versioned_docs/version-1.15/reference/spec/host-capabilities/06-kubernetes.md
Fix Doc issue, the operation is called "get_resource" singular per https://github.com/kubewarden/policy-evaluator/blob/3cd66b932b199037e677e3e204d4d9742e23edc8/src/runtimes/callback.rs#L276
None
None
None
> Fix the name of the get_resource operation

- docs/howtos/application-collection/01-verify-images.md
- docs/howtos/application-collection/_category_.json
- docs/howtos/policy-servers/02-private-registry.md
Add Rancher Application Collection subsection, add verify images page.
Clarify the usage of imagePullSecret for PolicyServers.
I have tested this commands by hand.
> Add Rancher Application Collection subsection, verify images

- docs/howtos/workarounds/policy-server-certificate-expiry.md
Updates the page about policy server certificate workaround stating that is valid only for Kubewarden v1.16.0 and earlier. Since v1.17.0, the certificate will be renewed automatically by the controller.
Related to https://github.com/kubewarden/docs/issues/252
> fix: certificate rotation workaround is fixed.

- docs/explanations/policy-groups.md
Adds a new page in the documentation explaining how the policy group types works.
Fix #448
> feat(docs): explanation page about policy groups.

- docs/howtos/telemetry/10-opentelemetry-qs.md
- docs/reference/dependency-matrix.md
From Kubewarden 1.18 We need minimum open-telemetry/opentelemetry-operator >= 0.104, shipped in the opentelemetry-operator chart 0.65.0, as we make use of opentelemetry.io/v1beta1 CRDs.
See: https://github.com/kubewarden/helm-charts/issues/579
This dep bump was untested, but we run the e2e tests against latest otel charts.
> Update otel chart dep to >= 0.65

- docs/howtos/pod-security-admission-with-kubewarden.md
- docs/howtos/secure-supply-chain.md
- docs/reference/monitor-mode.md
- docs/reference/verification-config.md
- docs/tutorials/writing-policies/go/04-validation.md
- docs/tutorials/writing-policies/go/09-validation-with-queries.md
- docs/tutorials/writing-policies/go/10-raw-policies.md
- docs/tutorials/writing-policies/rego/open-policy-agent/05-raw-policies.md
- docs/tutorials/writing-policies/rust/02-create-policy.md
- docs/tutorials/writing-policies/rust/04-write-validation-logic.md
- docs/tutorials/writing-policies/wasi/02-raw-policies.md
To be more in alignment with asciidoc, as used in product documentation for SUSE Admission Policy Manager.
To see the asciidoc version, for comparison, in product docs:  https://github.com/jhkrug/kubewarden-product-docs/blob/40c59ee37760b9bb28f0c56e3c4fc545a40661b0/docs/next/modules/en/pages/reference/monitor-mode.adoc?plain=1#L30-L58
> New approach to referencing content in code blocks. 

- versioned_docs/version-1.20/howtos/telemetry/10-opentelemetry-qs.md
- versioned_docs/version-1.20/howtos/telemetry/20-tracing-qs.md
- versioned_docs/version-1.20/howtos/telemetry/30-metrics-qs.md
- versioned_docs/version-1.20/howtos/telemetry/40-custom-otel-collector.md
Unfortunately some 1.20 contents were not merged by the time the versioned "branch" was created.
This commit ensures 1.20 contains the new contents about the advanced OpenTelemetry howto
> Backport doc changes to 1.20

- docs/reference/CRDs.md
- versioned_docs/version-1.17/reference/CRDs.md
- versioned_docs/version-1.18/reference/CRDs.md
- versioned_docs/version-1.19/reference/CRDs.md
- versioned_docs/version-1.20/reference/CRDs.md
The CRDs of the policy group were probably generated a bit earlier during the development cycle. In the beginning the policies part of the group were kept inside of an array, but later we moved to use a dictionary.
The documentation we shipped made reference to the array of policies, instead of the dictionary.
This commit fixes the issue also on the older releases, since we never ever shipped the CRD that used the list.
This is what the current documentation states for [`AdmissionPolicyGroupSpec`](https://docs.kubewarden.io/reference/CRDs#admissionpolicygroupspec), which is wrong:
This is what the new documentation [will show](https://deploy-preview-480--silly-bunny-8cedd0.netlify.app/reference/CRDs#admissionpolicygroupspec) instead:
Then, clicking on the …
> fix: group policies CRD definition was wrong

- updatecli/values.d/update-cli-ref-docs.yaml
Updates the updatecli values file to use the right labels in the PR created to update the CLI reference documentation.
> fix: labels for PR updating CLI docs.

- updatecli/update-cli-ref-docs.yaml
- updatecli/updatecli.d/headers.yaml
- updatecli/values.d/headers.yaml
- updatecli/values.d/update-cli-ref-docs.yaml
Updates the updatecli script to update the CLI reference documentation only when there is some change in the file.
> fix(ci): update CLI reference docs only when necessary.

- docs/explanations/policy-groups.md
clarify that context-aware capabilities are available using ClusterAdmissionPolicyGroup only
> docs: clarify that context-aware capabilities are available using ClusterAdmissionPolicyGroup only

- docs/introduction.md
New to Kubewarden section. As recommended by CNCF. Part of #477
> CNCF recommendation - New to Kubewarden.

- docs/quick-start.md
- versioned_docs/version-1.22/quick-start.md
In the quick-start (`/quick-start`), a new line was added in between the [required syntax](https://github.com/kubewarden/docs/blob/a1ac1a8b84727bbe7c1f9a2b6956dc3a83688f98/js-lib/docusaurus-variables.js#L11) for two variables, making them erroneously render as plain text
- move the whole variable to the next line to properly render it, matching how it was before https://github.com/kubewarden/docs/pull/539#discussion_r1976789946
<details><summary>Here's how it looked like <i>before</i> this change:</summary>
</details>
```sh
yarn start &
open http://localhost:3000/quick-start
```
n/a
n/a
> fix(quick-start): correctly render variables

- docs/reference/oci-registries-support.md
> CNCF active language review for OCI registries.

- docs/howtos/argocd-installation.md
- docs/howtos/security-hardening/_category_.json
- docs/howtos/security-hardening/webhook-mtls.md
- docs/reference/security-hardening/_category_.json
- docs/reference/security-hardening/webhook-mtls.md
- docs/reference/threat-model.md
Each link below points to the new page from our live preview:
Fixes https://github.com/kubewarden/docs/issues/540
Open questions for the reviewers:
- Is it worth to have a "Security" folder under "reference" and "howto" like I did? Should we just move the single document I wrote one level up?
- The reference doc: the name of the url and of the document mentions "mTLS", however this is much more, because we also have the optional network policies. Should we do a rename?
> Cover mTLS

- docs/reference/security-hardening/webhooks-hardening.md
- docs/reference/threat-model.md
Move to a different link, use a different name.
Fixes https://github.com/kubewarden/docs/issues/559
> doc: rename webhooks' hardening page

- docs/quick-start.md
Fix #563 
broken link of `ValidatingWebhookConfiguration`  is in https://docs.kubewarden.io/quick-start#example-enforce-your-first-policy
the broken link: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io
the new working link: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io
> fix broken link in quick start page

- docs/howtos/airgap/01-requirements.md
- docs/howtos/airgap/02-install.md
- docs/howtos/airgap/_category_.json
- docs/howtos/application-collection/_category_.json
- docs/howtos/argocd-installation.md
- docs/howtos/audit-scanner.md
- docs/howtos/pod-security-admission-with-kubewarden.md
- docs/howtos/policies.md
- docs/howtos/policy-groups.md
- docs/howtos/policy-servers/_category_.json
- docs/howtos/production-deployments.md
- docs/howtos/psp-migration.md
- docs/howtos/security-hardening/_category_.json
- docs/howtos/security-hardening/secure-supply-chain.md
- docs/howtos/security-hardening/security-hardening.md
- docs/howtos/security-hardening/webhook-mtls.md
- docs/howtos/ui-extension/01-install.md
- docs/howtos/ui-extension/_category_.json
- docs/howtos/vap-migration.md
- docs/howtos/workarounds/_category_.json
- docs/reference/spec/host-capabilities/02-signature-verifier-policies.md
- docs/reference/threat-model.md
- docs/reference/verification-config.md
Related to https://github.com/kubewarden/docs/issues/558.
While working on https://github.com/kubewarden/community/issues/40, I feel it's easier to provide a more featured security-hardening section than to write the contents of this PR in the self-assessment which is not so accessible.
Expanded with a summary on how to harden Kubewarden installations.
Reorder howtos/ section, from more general and newbie topics, to more specific and obscure.
> Expand security-hardening/ subsection, reorder howtos/ section

- docs/howtos/ui-extension/01-install.md
Remove outdated documentation about ArtifactHub from UI Extension quickstart.
Based on changes from https://github.com/rancher/kubewarden-ui/pull/1030
> Remove ArtifactHub from UI Extension docs

- updatecli/updatecli.d/headers.yaml
Updates the updatecli policy used to add the headers in the CLI reference documentation to remove the arrows added in the markdown files.
Related to #493
> fix: remove arrows from CLI reference documentation.

- .github/workflows/deploy.yml
Use actions/upload-pages-artifact for the publish dir to consume from actions/deploy-pages.
Part of https://github.com/kubewarden/kubewarden-controller/issues/1097.
Workflow run:
https://github.com/viccuad/docs/actions/runs/14836710802
Visible at:
https://viccuad.github.io/docs/
I didn't change the base URL config of docusaurus, and I believe that's why it isn't showing correctly. But I think it is fine.
> refactor: s#peaceiris/actions-gh-pages#actions/deploy-pages

- docs/howtos/security-hardening/security-hardening.md
Clarify the section about PSA, previously it was kinda conflated into the pod security context section, which was wrong.
[Link to the new section](https://deploy-preview-605--docs-kubewarden-io.netlify.app/next/howtos/security-hardening#pod-security-admission)
> docs: expand security hardening with PSA

- docs/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.10/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.11/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.12/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.13/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.14/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.15/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.16/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.17/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.18/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.19/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.20/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.21/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.22/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.23/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.24/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.25/tutorials/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.7/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.8/writing-policies/rust/04-write-validation-logic.md
- versioned_docs/version-1.9/writing-policies/rust/04-write-validation-logic.md
The original link is to v0.11.x which is now 404. I've updated it to v0.25.x. Is that OK? Lots of versions in between. I don't know if it makes difference or not.
> struct.Pod ref broken link fix.

- docs/howtos/policies.md
- docs/reference/CRDs.md
Adds a new section in the policies configuration documentation page describing how users can customize policy reject message.
Fix #624
> feat: custom rejection message documentation.

- docs/howtos/gatekeeper-migration.md
Adds a how to guide showing how users can migrate a Gatekeeper policy into Kubewarden policy.
Fix #621
> feat: Gatekeeper policy migration guide.

- docs/reference/policy-evaluation-timeout.md
> policy evaluation timeout language review for active voice as part of the CNCF recommendations.

- docs/reference/dependency-matrix.md
Last tested version of OTEL operator is 0.92.3, we can use it in our dependency metrics.
> Update OTEL operator in version matrix

- docs/tutorials/verifying-kubewarden.md
Fixed a typo in container registry URLs, changing `ghrc.io` to the correct `ghcr.io`.
CI
This change is a straightforward typo fix.
Consider adding tests or a linter to catch common domain typos in future PRs.
> fix(typo): ghcr.io

- docs/reference/dependency-matrix.md
There is a bug with combination of OTEL operator 0.92.3 + helm 3.18.5.
I bumped version in tests also to 0.93.0.
> Bump OTEL operator version

- docs/reference/spec/host-capabilities/05-crypto.md
Update the documentation of the verify function to reflect the change done with https://github.com/kubewarden/policy-evaluator/pull/744
> docs: update reference docs for the crypto host capability
